apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-api
  name: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adm-api
  strategy: {}
  template:
    metadata:
      labels: 
        app: adm-api
    spec:
      containers:
        - image: oshokumar/appointme-admin-api:1.1
          imagePullPolicy: "IfNotPresent"
          name: admin-api
          ports:
            - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  labels:
    svc: ame-adm-api-svc
  name: admin-api-svc
spec:
  type: NodePort
  selector: 
    app: adm-api
  ports:
  - name: http
    port: 5050
    targetPort: 5050
    nodePort: 30050

